language: sh

matrix:
  include:
    - os:
        - linux
        - osx
      script:
        - ./build-env/common.sh
        # Run script twice to test idempotency
        - ./build-env/common.sh

    - os: windows
      script:
        - ./build-env/windows/link.ps1
