language: sh

os:
  - linux
  - osx
  - windows

script:
  - |-
    case $TRAVIS_OS_NAME in
      windows)
        ./build-env/windows/link.ps1
      ;;
      linux|osx)
        ./build-env/common.sh
        # Run script twice to test idempotency
        ./build-env/common.sh
      ;;
