language: sh

addons:
  apt:
    packages:
      - zsh

matrix:
  include:
    - os: linux
    - os: osx
      script:
        - ./test/unix.sh

    - os: windows
      script:
        - powershell -ExecutionPolicy RemoteSigned -File ./build-env/windows/link.ps1
        # Run script twice to test idempotency
        - powershell -ExecutionPolicy RemoteSigned -File ./build-env/windows/link.ps1

script:
  - ./test/static.sh
  - ./test/unix.sh
