language: sh

matrix:
  include:
    - os: linux
    - os: osx

    - os: windows
      script:
        - powershell -ExecutionPolicy RemoteSigned -File ./build-env/windows/link.ps1
        # Run script twice to test idempotency
        - powershell -ExecutionPolicy RemoteSigned -File ./build-env/windows/link.ps1

script:
  - ./build-env/common.sh
    # Run script twice to test idempotency
  - ./build-env/common.sh
