brew "bat"
brew "chezmoi"
brew "colordiff"
brew "curl"
brew "deno"
brew "editorconfig"
brew "exiftool"
brew "fd"
brew "fswatch"
brew "fzf"
brew "gh"
brew "ghq"
brew "git"
brew "git-delta"
brew "git-lfs"
brew "gnu-tar"
brew "go-task"
brew "hadolint"
brew "htop"
brew "hub"
brew "jq"
brew "mercurial"
brew "mise"
brew "neovim"
brew "ripgrep"
brew "sheldon"
brew "shellcheck"
brew "socat"
brew "tig"
brew "vbindiff"
brew "xz"
brew "zsh"
brew "zx"

if OS.mac?
  tap "1password/tap"

  brew "autoconf"
  brew "automake"
  brew "cmake"
  brew "coreutils"
  brew "findutils"
  brew "gpg"
  brew "gnu-sed"
  brew "grep"
  brew "gzip"
  brew "libyaml" # ruby
  brew "rsync"
  brew "unzip"
  brew "wget"

  cask "1password-cli"
  cask "font-hackgen-nerd"
  cask "font-m-plus-1-code"
  cask "git-credential-manager"
end
