[tools]
"github:afadesigns/zshellcheck" = "1.7.1"
"github:goss-org/goss" = "0.4.9"
actionlint = "1.7.12"
dprint = "0.55.1"
hk = "1.49.0"
pkl = "0.31.1"
shellcheck = "0.11.0"
shfmt = "3.13.1"
zizmor = "1.26.1"

[tasks.cz]
run = "cz-clean-env --source $MISE_PROJECT_ROOT"
quiet = true

[tasks.zsh-bench]
run = "hyperfine -w 5 -r 50 'zsh -i -c exit'"

[tasks.zsh-prof]
run = "zsh -i -c exit"
env.ZPROF = "1"

[shell_alias]
cz = "mise run cz"
