[tools]
deno = "2.7.9"

"github:goss-org/goss" = "0.4.9"

[tasks.cz]
run = "cz-clean-env --source $MISE_PROJECT_ROOT"
quiet = true

[tasks.zsh-bench]
run = "hyperfine -w 5 -r 50 'zsh -i -c exit'"

[tasks.zsh-prof]
run = "zsh -i -c exit"
env.ZPROF = "1"

[shell_alias]
cz = "mise run cz"

[settings]
install_before = "1d"
