[[plugins]]
repo = 'Shougo/neocomplete.vim'
lazy = 1
on_i = 1
if = '''!has('nvim')'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
lazy = 1
on_i = 1
if = '''has('nvim')'''

[[plugins]]
repo = 'osyo-manga/vim-marching'
on_ft = [ 'c', 'cpp', 'objc', 'objcpp' ]

[[plugins]]
repo = 'h1mesuke/vim-alignta'
on_cmd = 'Alignta'

[[plugins]]
repo = 'Shougo/echodoc'
on_i = 1

[[plugins]]
repo = 'thinca/vim-quickrun'
on_map = '<Plug>'

[[plugins]]
repo = 'cohama/vim-hier'
[[plugins]]
repo = 'osyo-manga/shabadou.vim'
[[plugins]]
repo = 'osyo-manga/vim-watchdogs'
depends = [ 'vim-quickrun', 'shabadou.vim', 'vim-hier', ]
on_ft = [ 'c', 'cpanfile', 'cpp', 'javascript', 'perl', 'ruby', ]

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = [ 'css', 'haml', 'html', 'markdown', 'scss', 'tt2html', 'xml', 'xslate', ]

[[plugins]]
repo = 'anyakichi/vim-surround'
on_map = [
  '<Plug>SurroundRepeat', '<Plug>Dsurround', '<Plug>Csurround', '<Plug>Yssurround', '<Plug>Ygssurround', '<Plug>Ysurround', '<Plug>Ygsurround', '<Plug>Vsurround', '<Plug>VSurround', '<Plug>Vgsurround', '<Plug>VgSurround', '<Plug>Isurround', '<Plug>ISurround', ]

[[plugins]]
repo = 'LeafCage/yankround.vim'
on_map = '<Plug>'

[[plugins]]
repo = 'haya14busa/incsearch.vim'
on_map = '<Plug>'

[[plugins]]
repo = 'haya14busa/incsearch-fuzzy.vim'
on_map = '<Plug>'

[[plugins]]
repo = 'haya14busa/vim-migemo'
on_func = 'migemo#'

[[plugins]]
repo = 'haya14busa/incsearch-migemo.vim'
on_map = '<Plug>'

[[plugins]]
repo = 'godlygeek/tabular'
on_cmd = 'Tabularize'

[[plugins]]
repo = 'tyru/open-browser.vim'
on_map = '<Plug>(openbrowser'

[[plugins]]
repo = 'tyru/open-browser-github.vim'
on_cmd = [ 'OpenGithubFile', 'OpenGithubIssue', 'OpenGithubPullReq', 'OpenGithubProject', ]
depends = 'open-browser.vim'

# Unite {{{
[[plugins]]
repo = 'Shougo/unite.vim'
on_cmd = 'Unite'

[[plugins]]
repo = 'Shougo/unite-outline'
on_source = [ 'unite.vim' ]

[[plugins]]
repo = 'Shougo/unite-build'
on_source = [ 'unite.vim' ]

[[plugins]]
repo = 'hewes/unite-gtags'
on_source = [ 'unite.vim' ]

[[plugins]]
repo = 'lambdalisue/unite-grep-vcs'
on_source = [ 'unite.vim' ]

# }}}

# File types {{{
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = [ 'css', 'sass', 'scss', 'markdown' ]

[[plugins]]
repo = 'othree/html5.vim'
on_ft = [ 'html', 'markdown' ]

[[plugins]]
repo = 'joker1007/vim-markdown-quote-syntax'
on_ft = 'markdown'

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = 'markdown'

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = [ 'coffee', 'markdown' ]

[[plugins]]
repo = 'sophacles/vim-processing'
on_ft = 'processing'

[[plugins]]
repo = 'evanmiller/nginx-vim-syntax'
on_ft = 'nginx'

[[plugins]]
repo = 'gnuplot.vim'
on_ft = 'gnuplot'

[[plugins]]
repo = 'honza/dockerfile.vim'
on_ft = 'dockerfile'

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = [ 'javascript', 'markdown' ]

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repo = 'clausreinke/typescript-tools.vim'
on_ft = 'typescript'

[[plugins]]
repo = 'vim-perl/vim-perl'
on_ft = [ 'perl', 'cpanfile', 'tt2html' ]

[[plugins]]
repo = 'motemen/xslate-vim'
on_ft = 'xslate'

[[plugins]]
repo = 'moznion/vim-cpanfile'
on_ft = 'cpanfile'

[[plugins]]
repo = 'vim-jp/vim-go-extra'
on_cmd = [ 'Fmt', 'Godoc', 'Import' ]

[[plugins]]
repo = 'nsf/gocode'
on_ft = 'go'
rtp = 'vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

# }}}
