[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc'
if = '''!(has('win32') && has('kaoriya'))'''
build = 'make'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
if = '''!has('win32')'''
hook_source = '''
  if executable('editorconfig')
    let g:EditorConfig_core_mode = 'external_command'
  endif
'''

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  nnoremap <silent> <Leader>gc :<C-u>Gcommit<CR>
  nnoremap <silent> <Leader>gb :<C-u>Gblame<CR>
  nnoremap <silent> <Leader>gd :<C-u>Gdiff<CR>
  nnoremap <silent> <Leader>gs :<C-u>Gstatus<CR>
'''

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_enable_on_vim_startup = 1
  let g:indent_guides_guide_size = 1
  let g:indent_guides_start_level = 2
  let g:indent_guides_auto_colors = 0
  autocmd vimrc_loading VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=#fdf6e3 ctermbg=15
  autocmd vimrc_loading VimEnter,Colorscheme * :hi IndentGuidesEven guibg=#eee8d5 ctermbg=7
'''

[[plugins]]
repo = 'thinca/vim-template'

[[plugins]]
repo = 'Shougo/tabpagebuffer.vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'
hook_add = '''
  set background=light
  let g:solarized_termcolors=16
  let g:solarized_termtrans=1
  let g:solarized_italic=0
  autocmd vimrc_loading VimEnter * nested colorscheme solarized
'''
