[shell_alias]
ls = "ls -G"
base64 = "gbase64"
comm = "LC_ALL=C gcomm"
date = "gdate"
grep = "LC_ALL=C ggrep"
look = "LC_ALL=C look"
md5sum = "gmd5sum"
sed = "gsed"
sha1sum = "gsha1sum"
sha224sum = "gsha224sum"
sha256sum = "gsha256sum"
sha384sum = "gsha384sum"
sha512sum = "gsha512sum"
shuf = "gshuf"
sort = "LC_ALL=C gsort"
tail = "gtail"
uniq = "LC_ALL=C guniq"
wc = "gwc"
