[tools]
node = "24" # for npm
pnpm = "11"
"github:k1LoW/mo" = "latest"
"npm:ccstatusline" = "latest"
"npm:difit" = "latest"

uv = "latest"

claude = "latest"
usage = "latest"

[tools."github:mono0x/git-default-branch"]
version = "latest"
bin = "git-default-branch"

[settings]
experimental = true
disable_backends = ["asdf", "vfox"]
install_before = "1d"

[settings.npm]
package_manager = "pnpm"

[settings.pipx]
uvx = true

[settings.python]
compile = false

[shell_alias]
claude = "claude --enable-auto-mode"
