[tools]
aube = "1"
node = "24" # for npm
"github:k1LoW/mo" = "latest"
"npm:ccstatusline" = "latest"
"npm:difit" = "latest"

uv = "latest"

claude = "latest"
usage = "latest"

[tools."github:mono0x/git-default-branch"]
version = "latest"
bin = "git-default-branch"

[settings]
experimental = true
disable_backends = ["asdf", "vfox"]
install_before = "2d"

[settings.npm]
package_manager = "aube"

[settings.pipx]
uvx = true

[settings.python]
compile = false
