[[plugins]]
repo = 'anyakichi/vim-surround'
on_map = [
  '<Plug>Csurround',
  '<Plug>Dsurround',
  '<Plug>ISurround',
  '<Plug>Isurround',
  '<Plug>SurroundRepeat',
  '<Plug>VSurround',
  '<Plug>VgSurround',
  '<Plug>Vgsurround',
  '<Plug>Vsurround',
  '<Plug>Ygssurround',
  '<Plug>Ygsurround',
  '<Plug>Yssurround',
  '<Plug>Ysurround',
]
hook_add = '''
  nmap <unique> ds     <Plug>Dsurround
  nmap <unique> cs     <Plug>Csurround
  nmap <unique> ys     <Plug>Ysurround
  nmap <unique> yS     <Plug>Ysurround$
  nmap <unique> yss    <Plug>Yssurround
  nmap <unique> ygs    <Plug>Ygsurround
  nmap <unique> ygS    <Plug>Ygsurround$
  nmap <unique> ygss   <Plug>Ygssurround
  nmap <unique> ygsgs  <Plug>Ygssurround
  xmap <unique> s      <Plug>Vsurround
  xmap <unique> S      <Plug>VSurround
  xmap <unique> gs     <Plug>Vgsurround
  xmap <unique> gS     <Plug>VgSurround
  imap <unique> <C-S>  <Plug>Isurround
  imap <unique> <C-G>s <Plug>Isurround
  imap <unique> <C-G>S <Plug>ISurround
'''
hook_source = '''
  let g:surround_no_mappings = 1
'''

[[plugins]]
repo = 'tyru/open-browser.vim'
on_map = '<Plug>(openbrowser'
hook_add = '''
  nmap gx <Plug>(openbrowser-smart-search)
  vmap gx <Plug>(openbrowser-smart-search)

  let g:netrw_nogx = 1
'''

[[plugins]]
repo = 'tyru/open-browser-github.vim'
on_cmd = [
  'OpenGithubFile',
  'OpenGithubIssue',
  'OpenGithubProject',
  'OpenGithubPullReq',
]
depends = 'open-browser.vim'
hook_add = '''
  nnoremap <silent> <Leader>gh :OpenGithubFile<CR>
  vnoremap <silent> <Leader>gh :OpenGithubFile<CR>
'''
hook_source = '''
  let g:openbrowser_github_always_use_commit_hash = 1
  let g:openbrowser_github_url_exists_check = 'ignore'
'''
