name: Setup mise
description: Setup mise with version pinning
runs:
  using: composite
  steps:
    - uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3.5.1
      with:
        version: 2026.1.8
