update
upgrade

install ansible
install git
install htop-osx
install openssl
install peco/peco/peco
install postgresql
install pow
install rbenv
install readline
install ruby-build
install the_silver_searcher
install tmux
install wget
install xz
install zsh

install caskroom/cask/brew-cask
tap caskroom/versions

cask install appcleaner
cask install bittorrent-sync
cask install boot2docker
cask install dropbox
cask install firefox-ja
cask install google-chrome
cask install google-japanese-ime
cask install heroku-toolbelt
#cask install macvim-kaoriya
cask install mendeley-desktop
cask install onepassword
cask install skype
cask install vagrant
cask install virtualbox
#cask install vmware-fusion

cask cleanup
cleanup
