name: CI
on:
  push:
    branches:
      - "*"
  pull_request:
permissions:
  contents: read
jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          submodules: recursive
          persist-credentials: false
      - uses: ./.github/actions/setup-mise
      - name: "Workaround: Prepare ~/.local/share/chezmoi"
        run: |
          mkdir -p "$HOME/.local/share"
          ln -s "$(pwd)" "$HOME/.local/share/chezmoi"
      - name: Copy install.sh to outside of the repository
        run: |
          cp ./install.sh /tmp/install.sh
      - name: Run test
        uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4.0.0
        with:
          command: |
            cd /tmp
            ./install.sh
          max-attempts: 10
          delay-seconds: 5
      - name: Run test again to test idempotency
        working-directory: /tmp
        run: |
          ./install.sh
  test-static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-mise
      - name: Install dependencies
        run: sudo apt install -y zsh
      - run: |
          hk check --all
        env:
          HK_PKL_BACKEND: pklr
