name: CI
on:
  push:
    branches:
      - "main"
  pull_request:
permissions:
  contents: read
jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          submodules: recursive
          persist-credentials: false
      - uses: ./.github/actions/setup-mise
      - name: "Workaround: Prepare ~/.local/share/chezmoi"
        run: |
          mkdir -p "$HOME/.local/share"
          ln -s "$(pwd)" "$HOME/.local/share/chezmoi"
          echo "CHEZMOI_SOURCE_DIR=$HOME/.local/share/chezmoi" >> "$GITHUB_ENV"
      - name: Trust
        working-directory: ${{ env.CHEZMOI_SOURCE_DIR }}
        run: |
          mise trust
      - name: Run bootstrap
        working-directory: ${{ env.CHEZMOI_SOURCE_DIR }}
        run: |
          mise bootstrap
      - name: Run bootstrap again to test idempotency
        working-directory: ${{ env.CHEZMOI_SOURCE_DIR }}
        run: |
          mise bootstrap
  test-static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-mise
      - name: Install dependencies
        run: sudo apt install -y zsh
      - run: |
          hk check --all
        env:
          HK_PKL_BACKEND: pklr
