name: test
on:
  push:
    branches:
      - "*"

jobs:
  test-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1
      - name: "Workaround: Prepare ~/.local/share/chezmoi"
        run: |
          mkdir -p "$HOME/.local/share"
          ln -s "$(pwd)" "$HOME/.local/share/chezmoi"
      - uses: jdx/mise-action@5083fe46898c414b2475087cc79da59e7da859e8 # v2.1.11
      - name: Install dependencies
        run: |
          sudo apt install -y zsh
      - name: Install goss
        run: |
          sudo curl -L https://github.com/goss-org/goss/releases/latest/download/goss-linux-amd64 -o /usr/local/bin/goss
          sudo chmod +rx /usr/local/bin/goss
      - name: Run test
        run: |
          ./install.sh
          # Run script twice to test idempotency
          ./install.sh
          goss validate --format documentation

  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1
      - name: "Workaround: Prepare ~/.local/share/chezmoi"
        run: |
          mkdir -p "$HOME/.local/share"
          ln -s "$(pwd)" "$HOME/.local/share/chezmoi"
      - uses: jdx/mise-action@5083fe46898c414b2475087cc79da59e7da859e8 # v2.1.11
      - name: Install goss
        run: |
          sudo curl -L https://github.com/goss-org/goss/releases/latest/download/goss-darwin-amd64 -o /usr/local/bin/goss
          sudo chmod +rx /usr/local/bin/goss
      - name: Run test
        run: |
          ./install.sh
          # Run script twice to test idempotency
          ./install.sh
          GOSS_USE_ALPHA=1 goss validate --format documentation

  test-windows:
    runs-on: windows-latest
    env:
      SKIP_SCOOP: "true"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1
      - name: "Workaround: Prepare ~/.local/share/chezmoi"
        run: |
          New-Item -ItemType Directory -Force -Path "$env:USERPROFILE\.local\share"
          New-Item -ItemType SymbolicLink -Value (Get-Location) -Path "$env:USERPROFILE\.local\share\chezmoi"
      - name: Run test
        run: |
          pwsh -ExecutionPolicy RemoteSigned -File ./install.ps1
          # Run script twice to test idempotency
          pwsh -ExecutionPolicy RemoteSigned -File ./install.ps1

  test-static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1
      - uses: jdx/mise-action@5083fe46898c414b2475087cc79da59e7da859e8 # v2.1.11
      - name: Install dependencies
        run: sudo apt install -y zsh
      - name: Run test
        run: deno run -A ./test/static.ts

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash
      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
        shell: bash
