name: test
on:
  push:
    branches:
      - "*"

jobs:
  test-devcontainer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - run: npx zx ./test/devcontainer.mjs

  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - run: |
          sudo apt install -y zsh
          curl -fsSL https://goss.rocks/install | GOSS_DST="~/bin" sh
      - run: npx zx ./test/unix.mjs
      - run: "~/bin/goss" --gossfile test/goss/unix.yaml validate --format documentation

  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - run: |
          curl -fsSL https://goss.rocks/install | GOSS_DST="~/bin" sh
      - run: npx zx ./test/unix.mjs
      - run: "~/bin/goss" --gossfile test/goss/unix.yaml validate --format documentation

  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - run: powershell -ExecutionPolicy RemoteSigned -File ./build-env/windows/link.ps1
      # Run script twice to test idempotency
      - run: powershell -ExecutionPolicy RemoteSigned -File ./build-env/windows/link.ps1

  test-static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - run: sudo apt install -y zsh
      - run: npx zx ./test/static.mjs

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash
      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
        shell: bash
