name: test
on:
  push:
    branches:
      - "*"

jobs:
  test-devcontainer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - run: sudo apt install -y zsh
      - run: ./test/devcontainer.sh

  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - run: sudo apt install -y zsh
      - run: ./test/unix.sh

  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - run: ./test/unix.sh

  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - run: powershell -ExecutionPolicy RemoteSigned -File ./build-env/windows/link.ps1
      # Run script twice to test idempotency
      - run: powershell -ExecutionPolicy RemoteSigned -File ./build-env/windows/link.ps1

  test-static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - run: sudo apt install -y zsh
      - run: ./test/static.sh
